packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  dprint: true
  esbuild: true
  svelte-preprocess: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - tiddlywiki-plugin-dev@0.5.12
