import fs from 'fs';
import path from 'path';
import { tmpdir } from 'os';
import UglifyJS from 'uglify-js';
import { program } from 'commander';
import { minify as htmlMinify } from 'html-minifier-terser';
import { tryCopy, mkdirsForFileSync, tiddlywiki } from './utils';

const waitForFile = (path: string) =>
  new Promise<void>(resolve => {
    const id = setInterval(() => {
      resolve();
      if (fs.existsSync(path)) {
        resolve();
        clearInterval(id);
      }
    }, 100);
  });

const htmlMinifierOptions = {
  caseSensitive: true,
  collapseBooleanAttributes: false,
  collapseInlineTagWhitespace: false,
  collapseWhitespace: true,
  conservativeCollapse: true,
  continueOnParseError: true,
  customAttrCollapse: /.*/,
  decodeEntities: true,
  html5: true,
  ignoreCustomFragments: [/<#[\s\S]*?#>/, /<%[\s\S]*?%>/, /<\?[\s\S]*?\?>/],
  includeAutoGeneratedTags: false,
  keepClosingSlash: false,
  maxLineLength: 0,
  minifyCSS: true,
  minifyJS: true,
  minifyURLs: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: true,
  processScripts: ['text/html'],
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeEmptyElements: false,
  removeOptionalTags: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  removeTagWhitespace: true,
  sortAttributes: true,
  sortClassName: true,
  trimCustomFragments: true,
  useShortDoctype: true,
};

/** 项目路径 */
const repoFolder = process.cwd();
const wikiFolder = path.resolve(repoFolder, 'wiki');
const publicFolder = path.resolve(repoFolder, 'public');
const tiddlersFolder = path.resolve(wikiFolder, 'tiddlers');

/**
 * 构建在线HTML版本：核心JS和资源文件不包括在HTML中， 下载后不能使用
 * @param {string} dist 目标路径，空或者不填则默认为'dist'
 * @param {string} htmlName HTML名称，空或者不填则默认为'index.html'
 * @param {boolean} minify 是否最小化JS和HTML，默认为true
 * @param {string} excludeFilter 要排除的tiddler的过滤表达式，默认为'-[is[draft]]'
 */
const buildOnlineHTML = async (
  dist = 'dist',
  htmlName = 'index.html',
  minify = true,
  excludeFilter = '-[is[draft]]',
) => {
  const distDir = path.resolve(dist);

  // 静态资源拷贝
  mkdirsForFileSync(path.resolve(distDir, htmlName));
  tryCopy(publicFolder, distDir);
  tryCopy(
    path.resolve(tiddlersFolder, 'favicon.ico'),
    path.resolve(distDir, 'favicon.ico'),
  );
  tryCopy(
    path.resolve(tiddlersFolder, 'TiddlyWikiIconWhite.png'),
    path.resolve(distDir, 'TiddlyWikiIconWhite.png'),
  );
  tryCopy(
    path.resolve(tiddlersFolder, 'TiddlyWikiIconBlack.png'),
    path.resolve(distDir, 'TiddlyWikiIconBlack.png'),
  );

  // 构建HTML
  // 备份 因为下面有改变tiddler的field的操作(媒体文件全部转为canonical)
  const backupFolder = fs.mkdtempSync(path.resolve(tmpdir(), 'tiddlywiki-'));
  tryCopy(tiddlersFolder, backupFolder);
  const $tw = tiddlywiki([], wikiFolder, [
    ...['--output', distDir] /* 指定输出路径 */,
    ...[
      '--deletetiddlers',
      '[[$:/UpgradeLibrary]] [[$:/UpgradeLibrary/List]]',
    ] /* 删掉一些没必要导出而且占用很大的条目 */,
    ...[
      '--setfield',
      '[is[image]] [is[binary]] [type[application/msword]] [type[image/svg+xml]]',
      '_canonical_uri',
      '$:/core/templates/canonical-uri-external-image',
      'text/plain',
    ] /* 媒体条目转外链 */,
    ...[
      '--setfield',
      '[is[image]] [is[binary]] [type[application/msword]] [type[image/svg+xml]]',
      'text',
      '',
      'text/plain',
    ] /* 媒体条目内容清空：注意这一步也会把所有媒体文件的内容变成空的 */,
    ...[
      '--rendertiddler',
      '$:/core/save/offline-external-js',
      htmlName,
      'text/plain',
      '',
      'publishFilter',
      excludeFilter,
    ] /* 导出无核心的HTML文件 */,
    ...[
      '--rendertiddler',
      '$:/core/templates/tiddlywiki5.js',
      'tiddlywikicore.js',
      'text/plain',
    ] /* 导出核心 */,
  ]);

  const rawCoreJsPath = path.join(distDir, 'tiddlywikicore.js');
  await waitForFile(rawCoreJsPath);

  // 将所有的二进制文件(媒体文件, 参考$tw.utils.registerFileType)导出
  const binaryExtensionMap: Record<string, boolean> = {};
  Object.keys($tw.config.fileExtensionInfo).forEach(ext => {
    const _info = $tw.config.fileExtensionInfo[ext];
    const info = $tw.config.contentTypeInfo[_info.type];
    if (info?.encoding === 'base64') {
      binaryExtensionMap[ext.toLowerCase()] = true;
    }
  });
  const distMediaFolder = path.resolve(distDir, 'images');
  mkdirsForFileSync(path.resolve(distMediaFolder, '1'));
  fs.cpSync(backupFolder, distMediaFolder, {
    force: true,
    recursive: true,
    filter: (src, _dest) =>
      src === backupFolder ||
      binaryExtensionMap[path.extname(src).toLowerCase()] === true,
  });

  // 恢复被清空内容的媒体文件
  tryCopy(backupFolder, tiddlersFolder);
  fs.rmSync(backupFolder, { recursive: true, force: true });

  // 最小化：核心JS和HTML
  if (minify) {
    // 核心
    const { code } = UglifyJS.minify(
      fs.readFileSync(rawCoreJsPath).toString('utf-8'),
      {
        warnings: false,
        ie8: true,
        webkit: true,
      },
    );
    fs.writeFileSync(rawCoreJsPath, code);
    // 网页
    const rawHTMLPath = path.join(distDir, htmlName);
    const html = await htmlMinify(
      fs.readFileSync(rawHTMLPath).toString('utf-8'),
      htmlMinifierOptions,
    );
    fs.writeFileSync(rawHTMLPath, html);
  }
  fs.renameSync(
    rawCoreJsPath,
    path.join(distDir, `tiddlywikicore-${($tw as any).packageInfo.version}.js`),
  );
};

/**
 * 构建离线HTML版本：核心JS和资源文件包括在HTML中， 下载后可以使用(就是单文件版本的wiki)
 * @param {string} dist 目标路径，空或者不填则默认为'dist'
 * @param {string} htmlName HTML名称，空或者不填则默认为'index.html'
 * @param {boolean} minify 是否最小化JS和HTML，默认为true
 * @param {string} excludeFilter 要排除的tiddler的过滤表达式，默认为'-[is[draft]]'
 */
const buildOfflineHTML = async (
  dist = 'dist',
  htmlName = 'index.html',
  minify = true,
  excludeFilter = '-[is[draft]]',
) => {
  const distDir = path.resolve(dist);
  // 构建HTML
  mkdirsForFileSync(path.resolve(distDir, htmlName));
  tiddlywiki([], wikiFolder, [
    ...['--output', distDir] /* 指定输出路径 */,
    ...[
      '--deletetiddlers',
      "'[[$:/UpgradeLibrary]] [[$:/UpgradeLibrary/List]]'",
    ] /* 删掉一些没必要导出而且占用很大的条目 */,
    ...[
      '--rendertiddler',
      '$:/plugins/tiddlywiki/tiddlyweb/save/offline',
      htmlName,
      'text/plain',
      '',
      'publishFilter',
      excludeFilter,
    ] /* 将wiki导出为HTML */,
  ]);

  // 最小化：HTML
  const rawHTMLPath = path.join(distDir, htmlName);
  await waitForFile(rawHTMLPath);
  if (minify) {
    const result = await htmlMinify(
      fs.readFileSync(rawHTMLPath).toString('utf-8'),
      htmlMinifierOptions,
    );
    fs.writeFileSync(rawHTMLPath, result);
  }
};

/**
 * 构建插件源
 * @param {string} pluginFilter 要发布插件的过滤器，默认为 '[prefix[$:/plugins/]!prefix[$:/plugins/tiddlywiki/]!prefix[$:/languages/]!prefix[$:/themes/tiddlywiki/]!tag[$:/tags/PluginLibrary]]'
 * @param {string} dist 目标路径，空或者不填则默认为'dist/library'
 * @param {boolean} minify 是否最小化HTML，默认为true
 */
const buildLibrary = async (
  pluginFilter = '[prefix[$:/plugins/]!prefix[$:/plugins/tiddlywiki/]!prefix[$:/languages/]!prefix[$:/themes/tiddlywiki/]!tag[$:/tags/PluginLibrary]]',
  dist = 'dist/library',
  minify = true,
) => {
  const distDir = path.resolve(dist);

  // 构建HTML
  mkdirsForFileSync(path.resolve(distDir, 'recipes/library/tiddlers'));
  tiddlywiki([], wikiFolder, [
    ...['--output', distDir] /* 指定输出路径 */,
    ...['--makelibrary', '$:/UpgradeLibrary'] /* 收集所有已安装插件 */,
    ...[
      '--savelibrarytiddlers',
      '$:/UpgradeLibrary',
      pluginFilter,
      'recipes/library/tiddlers/',
      '$:/UpgradeLibrary/List',
    ] /* 导出指定的插件 */,
    ...[
      '--savetiddler',
      '$:/UpgradeLibrary/List',
      'recipes/library/tiddlers.json',
    ] /* 生成插件集合JSON文件 */,
    ...[
      '--rendertiddler',
      '$:/plugins/tiddlywiki/pluginlibrary/library.template.html',
      'index.html',
      'text/plain',
    ] /* 生成插件库HTML文件 */,
    ...[
      '--deletetiddlers',
      '[[$:/UpgradeLibrary]] [[$:/UpgradeLibrary/List]]',
    ] /* 删掉中间内容 */,
  ]);

  // 最小化：HTML
  const rawHTMLPath = path.resolve(distDir, 'index.html');
  await waitForFile(rawHTMLPath);
  if (minify) {
    const result = await htmlMinify(
      fs.readFileSync(rawHTMLPath).toString('utf-8'),
      htmlMinifierOptions,
    );
    fs.writeFileSync(rawHTMLPath, result);
  }
};

program
  .command('publish')
  .description('Publish wiki')
  .argument('[dist]', 'Destination folder to publish', 'dist')
  .option(
    '-e, --exclude <exclude-filter>',
    'Filter to exclude publishing tiddlers',
    '-[is[draft]]',
  )
  .option('--minify', 'Should minify generated files', true)
  .option(
    '--offline',
    'Generate single wiki file, with an external core js file',
    false,
  )
  .action(
    async (
      dist: string,
      {
        offline,
        minify,
        excludeFilter,
      }: { offline: boolean; excludeFilter: string; minify: boolean },
    ) => {
      if (offline) {
        buildOfflineHTML(dist, 'index.html', minify, excludeFilter);
      } else {
        buildOnlineHTML(dist, 'index.html', minify, excludeFilter);
      }
    },
  )
  .parse();
